; File system root Directory
; This should in the future be generated by another program
; 1 Entry = 10 bytes 
FileName: db "SYSTM"
Attributes: db 0b11000000 ; or 0b00000011 I forgot how bit fields work
StartSect: dw 0
SectCount: dw 1

; 51 10 byte entries
EmptyEntries: times 510 db 0
NextTable: dw 0
